tech_companies = [
    "Apple",
    "Microsoft",
    "Google",
    "Amazon",
    "Facebook",
    "Samsung",
    "Intel",
    "IBM",
    "Oracle",
    "Cisco",
    "Adobe",
    "Netflix",
    "Tesla",
    "Nvidia",
    "HP",
    "Dell",
    "Sony",
    "Uber",
    "Airbnb",
    "SpaceX",
    # "Twitter",
    "Snap Inc.",
    "LinkedIn",
    "Reddit",
    "Alibaba",
    "Tencent",
    "Baidu",
    "Xiaomi",
    "PayPal",
    "Salesforce",
    "VMware",
    "Qualcomm",
    "Dropbox",
    "Ebay",
    "Square",
    "Slack",
    "Pinterest",
    "Zoom",
    "Palantir",
    "Lyft",
    "Stripe",
    "Zynga",
    "Etsy",
    "Razer",
    "Roblox",
    "Activision Blizzard",
    "Electronic Arts",
    "Unity Technologies"
]